# Generated by Django 3.1.2 on 2020-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriologist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
