# Generated by Django 3.1.2 on 2020-11-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_cita', models.DateField()),
                ('hora_de_cita', models.CharField(blank=True, max_length=15)),
                ('motivo_de_cita', models.CharField(blank=True, max_length=40, null=True)),
                ('dctos_asignados', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('nutriologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.nutriologist')),
            ],
        ),
    ]
